#include "soc/soc_ulp.h"
#include "soc/rtc_io_reg.h"
#include "soc/sens_reg.h"
#include "soc/rtc_cntl_reg.h"


.bss //Declaracao de variaveis


.text

    .global main
    main: //Inicio do codigo (Entry point)



    loop:

        //GPIO 2 = LOW
        WRITE_RTC_REG(RTC_GPIO_OUT_W1TC_REG, RTC_GPIO_OUT_DATA_W1TC_S+12, 1, 1)
        
        //500ms delay
        stage_rst
        1: stage_inc 1
        wait 32000
        jumps 1b, 125, lt


        //GPIO 2 = HIGH
        WRITE_RTC_REG(RTC_GPIO_OUT_W1TS_REG, RTC_GPIO_OUT_DATA_W1TS_S+12, 1, 1)

        //500ms delay
        stage_rst
        1: stage_inc 1
        wait 32000
        jumps 1b, 125, lt





    jump loop //retorna ao inicio do loop